### ISSUE TITLE
Add IMDB movie id

### ISSUE THREAD

**Issue by jocomet** [sp1thas/criticker-dataset#23]
This would open a huge door for me if it was able to scrape the imdb tconst from the page as well. For example 'tt0246578' from 'https://www.imdb.com/title/tt0246578/' on https://www.criticker.com/film/Donnie-Darko/

**Comment by jocomet** [comment]
`<meta itemprop='sameAs' content='https://www.imdb.com/title/tt0246578/' />
         <p class='fi_extrainfo' id='fi_info_ext'>More information at <a href='[https://www.imdb.com/title/tt0246578/](view-source:https://www.imdb.com/title/tt0246578/)' target='extwin'>IMDb</a></p>`

**Comment by sp1thas** [comment]
Still can not find this piece of imformation :/ I can see the IMDB urls about the directors and the cast but not about the movie itself.

Can you give the output of the following?

```python
import requests
url = 'https://www.criticker.com/film/Donnie-Darko/'
r = requests.get(url)
html = r.text
'tt0246578' in html
```

**Comment by jocomet** [comment]
Hmmm. I got false. But if I view the source of the page it is there as I copied above.

**Comment by jocomet** [comment]
The full div is:

`<div id='ti_justwatch_footer'>Powered by <a href='[https://justwatch.com/ca/movie/donnie-darko](view-source:https://justwatch.com/ca/movie/donnie-darko)' target='jw_win'><img src='[https://www.criticker.com/img/sys/justwatch-logo.png](view-source:https://www.criticker.com/img/sys/justwatch-logo.png)' alt='JustWatch'></a></div></div>
 <h2 class='fi_infohead' id='fi_extrainfo_header'>Updates, Links and Other Actions</h2>
     <p class='fi_extrainfo' id='fi_submitter'>Last modified by <a href='[https://www.criticker.com/profile/tjustt/](view-source:https://www.criticker.com/profile/tjustt/)'>TjustT</a> <span>(<a id='fi_loadhistory' href='[#](view-source:https://www.criticker.com/film/Donnie-Darko/#)'>View Update History</a>)</span></p>
     <p id='fi_history'>Loading... <img alt='loading' src='[https://www.criticker.com/img/sys/spinner.gif](view-source:https://www.criticker.com/img/sys/spinner.gif)' width="16" height="16"></p>
         <meta itemprop='sameAs' content='https://www.imdb.com/title/tt0246578/' />
         <p class='fi_extrainfo' id='fi_info_ext'>More information at <a href='[https://www.imdb.com/title/tt0246578/](view-source:https://www.imdb.com/title/tt0246578/)' target='extwin'>IMDb</a></p>
 <p class='fi_extrainfo'>Add <em>Donnie Darko</em> to your <a class='fi_watchlist_link' href='[https://www.criticker.com/film/Donnie-Darko/?mark=4](view-source:https://www.criticker.com/film/Donnie-Darko/?mark=4)'>Criticker Watchlist</a></p>
</div>`

**Comment by jocomet** [comment]
It is within 'div id='ti_justwatch_footer''

**Comment by jocomet** [comment]
Either you just need to be logged in or you need to be a supporter (which I am). When I log out that info amongst others is gone.

I would love to see something that showed imdb = tmdb = letterboxd = criticker = etc

The tmdb data export shows imdb. Both letterboxd and criticker import by imdb.
